[project]
name = "bd-stubs"
version = "0.1.2"
description = "A type stub repository for Ballsdex."
readme = "README.md"
authors = [
    { name = "Cayla", email = "official.dotzz@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "django-stubs>=6.1.1",
]
classifiers = [
    "Typing :: Stubs Only",
]

[project.optional-dependencies]
all = [
    "discord-py>=2.7.1",
    "prometheus-client>=0.26.0",
]

[dependency-groups]
dev = [
    "ruff>=0.16.9",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = [
    "src/ballsdex-stubs",
    "src/bd_models-stubs",
    "src/settings-stubs",
    "src/users-stubs",
]

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py313"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true
docstring-code-format = true

[tool.ruff.lint]
select = ["E", "F", "I", "W"]
ignore = ["E203"]

[tool.ruff.lint.isort]
split-on-trailing-comma = false
